/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BestStrikersRouteImport } from './routes/best-strikers'
import { Route as BestPlayersRouteImport } from './routes/best-players'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as AuthenticatedTournamentsRouteImport } from './routes/_authenticated/tournaments'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedRankingsRouteImport } from './routes/_authenticated/rankings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMyStatsRouteImport } from './routes/_authenticated/my-stats'
import { Route as AuthenticatedMatchesRouteImport } from './routes/_authenticated/matches'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedJoinTeamRouteImport } from './routes/_authenticated/join-team'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTournamentsIndexRouteImport } from './routes/_authenticated/tournaments.index'
import { Route as AuthenticatedTeamsIndexRouteImport } from './routes/_authenticated/teams.index'
import { Route as AuthenticatedMatchesIndexRouteImport } from './routes/_authenticated/matches.index'
import { Route as AuthenticatedTournamentsNewRouteImport } from './routes/_authenticated/tournaments.new'
import { Route as AuthenticatedTournamentsTournamentIdRouteImport } from './routes/_authenticated/tournaments.$tournamentId'
import { Route as AuthenticatedTeamsNewRouteImport } from './routes/_authenticated/teams.new'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams.$teamId'
import { Route as AuthenticatedMatchesNewRouteImport } from './routes/_authenticated/matches.new'
import { Route as AuthenticatedTeamsTeamIdMatchesRouteImport } from './routes/_authenticated/teams.$teamId.matches'
import { Route as AuthenticatedMatchesMatchIdSquadRouteImport } from './routes/_authenticated/matches.$matchId.squad'
import { Route as AuthenticatedMatchesMatchIdScoreRouteImport } from './routes/_authenticated/matches.$matchId.score'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BestStrikersRoute = BestStrikersRouteImport.update({
  id: '/best-strikers',
  path: '/best-strikers',
  getParentRoute: () => rootRouteImport,
} as any)
const BestPlayersRoute = BestPlayersRouteImport.update({
  id: '/best-players',
  path: '/best-players',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTournamentsRoute =
  AuthenticatedTournamentsRouteImport.update({
    id: '/tournaments',
    path: '/tournaments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingsRoute = AuthenticatedRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyStatsRoute = AuthenticatedMyStatsRouteImport.update({
  id: '/my-stats',
  path: '/my-stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchesRoute = AuthenticatedMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJoinTeamRoute = AuthenticatedJoinTeamRouteImport.update({
  id: '/join-team',
  path: '/join-team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTournamentsIndexRoute =
  AuthenticatedTournamentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTournamentsRoute,
  } as any)
const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTeamsRoute,
} as any)
const AuthenticatedMatchesIndexRoute =
  AuthenticatedMatchesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMatchesRoute,
  } as any)
const AuthenticatedTournamentsNewRoute =
  AuthenticatedTournamentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedTournamentsRoute,
  } as any)
const AuthenticatedTournamentsTournamentIdRoute =
  AuthenticatedTournamentsTournamentIdRouteImport.update({
    id: '/$tournamentId',
    path: '/$tournamentId',
    getParentRoute: () => AuthenticatedTournamentsRoute,
  } as any)
const AuthenticatedTeamsNewRoute = AuthenticatedTeamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedTeamsRoute,
} as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => AuthenticatedTeamsRoute,
  } as any)
const AuthenticatedMatchesNewRoute = AuthenticatedMatchesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedMatchesRoute,
} as any)
const AuthenticatedTeamsTeamIdMatchesRoute =
  AuthenticatedTeamsTeamIdMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedTeamsTeamIdRoute,
  } as any)
const AuthenticatedMatchesMatchIdSquadRoute =
  AuthenticatedMatchesMatchIdSquadRouteImport.update({
    id: '/$matchId/squad',
    path: '/$matchId/squad',
    getParentRoute: () => AuthenticatedMatchesRoute,
  } as any)
const AuthenticatedMatchesMatchIdScoreRoute =
  AuthenticatedMatchesMatchIdScoreRouteImport.update({
    id: '/$matchId/score',
    path: '/$matchId/score',
    getParentRoute: () => AuthenticatedMatchesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/best-players': typeof BestPlayersRoute
  '/best-strikers': typeof BestStrikersRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/join-team': typeof AuthenticatedJoinTeamRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/matches': typeof AuthenticatedMatchesRouteWithChildren
  '/my-stats': typeof AuthenticatedMyStatsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/tournaments': typeof AuthenticatedTournamentsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/matches/new': typeof AuthenticatedMatchesNewRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/teams/new': typeof AuthenticatedTeamsNewRoute
  '/tournaments/$tournamentId': typeof AuthenticatedTournamentsTournamentIdRoute
  '/tournaments/new': typeof AuthenticatedTournamentsNewRoute
  '/matches/': typeof AuthenticatedMatchesIndexRoute
  '/teams/': typeof AuthenticatedTeamsIndexRoute
  '/tournaments/': typeof AuthenticatedTournamentsIndexRoute
  '/matches/$matchId/score': typeof AuthenticatedMatchesMatchIdScoreRoute
  '/matches/$matchId/squad': typeof AuthenticatedMatchesMatchIdSquadRoute
  '/teams/$teamId/matches': typeof AuthenticatedTeamsTeamIdMatchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/best-players': typeof BestPlayersRoute
  '/best-strikers': typeof BestStrikersRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/join-team': typeof AuthenticatedJoinTeamRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/my-stats': typeof AuthenticatedMyStatsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/matches/new': typeof AuthenticatedMatchesNewRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/teams/new': typeof AuthenticatedTeamsNewRoute
  '/tournaments/$tournamentId': typeof AuthenticatedTournamentsTournamentIdRoute
  '/tournaments/new': typeof AuthenticatedTournamentsNewRoute
  '/matches': typeof AuthenticatedMatchesIndexRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
  '/tournaments': typeof AuthenticatedTournamentsIndexRoute
  '/matches/$matchId/score': typeof AuthenticatedMatchesMatchIdScoreRoute
  '/matches/$matchId/squad': typeof AuthenticatedMatchesMatchIdSquadRoute
  '/teams/$teamId/matches': typeof AuthenticatedTeamsTeamIdMatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/best-players': typeof BestPlayersRoute
  '/best-strikers': typeof BestStrikersRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/join-team': typeof AuthenticatedJoinTeamRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/matches': typeof AuthenticatedMatchesRouteWithChildren
  '/_authenticated/my-stats': typeof AuthenticatedMyStatsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rankings': typeof AuthenticatedRankingsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/_authenticated/tournaments': typeof AuthenticatedTournamentsRouteWithChildren
  '/auth_/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/_authenticated/matches/new': typeof AuthenticatedMatchesNewRoute
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/_authenticated/teams/new': typeof AuthenticatedTeamsNewRoute
  '/_authenticated/tournaments/$tournamentId': typeof AuthenticatedTournamentsTournamentIdRoute
  '/_authenticated/tournaments/new': typeof AuthenticatedTournamentsNewRoute
  '/_authenticated/matches/': typeof AuthenticatedMatchesIndexRoute
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute
  '/_authenticated/tournaments/': typeof AuthenticatedTournamentsIndexRoute
  '/_authenticated/matches/$matchId/score': typeof AuthenticatedMatchesMatchIdScoreRoute
  '/_authenticated/matches/$matchId/squad': typeof AuthenticatedMatchesMatchIdSquadRoute
  '/_authenticated/teams/$teamId/matches': typeof AuthenticatedTeamsTeamIdMatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/best-players'
    | '/best-strikers'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/admin'
    | '/dashboard'
    | '/feed'
    | '/join-team'
    | '/leaderboard'
    | '/matches'
    | '/my-stats'
    | '/profile'
    | '/rankings'
    | '/search'
    | '/teams'
    | '/tournaments'
    | '/auth/callback'
    | '/blog/$slug'
    | '/match/$matchId'
    | '/players/$playerId'
    | '/matches/new'
    | '/teams/$teamId'
    | '/teams/new'
    | '/tournaments/$tournamentId'
    | '/tournaments/new'
    | '/matches/'
    | '/teams/'
    | '/tournaments/'
    | '/matches/$matchId/score'
    | '/matches/$matchId/squad'
    | '/teams/$teamId/matches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/best-players'
    | '/best-strikers'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/admin'
    | '/dashboard'
    | '/feed'
    | '/join-team'
    | '/leaderboard'
    | '/my-stats'
    | '/profile'
    | '/rankings'
    | '/search'
    | '/auth/callback'
    | '/blog/$slug'
    | '/match/$matchId'
    | '/players/$playerId'
    | '/matches/new'
    | '/teams/$teamId'
    | '/teams/new'
    | '/tournaments/$tournamentId'
    | '/tournaments/new'
    | '/matches'
    | '/teams'
    | '/tournaments'
    | '/matches/$matchId/score'
    | '/matches/$matchId/squad'
    | '/teams/$teamId/matches'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/best-players'
    | '/best-strikers'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/feed'
    | '/_authenticated/join-team'
    | '/_authenticated/leaderboard'
    | '/_authenticated/matches'
    | '/_authenticated/my-stats'
    | '/_authenticated/profile'
    | '/_authenticated/rankings'
    | '/_authenticated/search'
    | '/_authenticated/teams'
    | '/_authenticated/tournaments'
    | '/auth_/callback'
    | '/blog/$slug'
    | '/match/$matchId'
    | '/players/$playerId'
    | '/_authenticated/matches/new'
    | '/_authenticated/teams/$teamId'
    | '/_authenticated/teams/new'
    | '/_authenticated/tournaments/$tournamentId'
    | '/_authenticated/tournaments/new'
    | '/_authenticated/matches/'
    | '/_authenticated/teams/'
    | '/_authenticated/tournaments/'
    | '/_authenticated/matches/$matchId/score'
    | '/_authenticated/matches/$matchId/squad'
    | '/_authenticated/teams/$teamId/matches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BestPlayersRoute: typeof BestPlayersRoute
  BestStrikersRoute: typeof BestStrikersRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-strikers': {
      id: '/best-strikers'
      path: '/best-strikers'
      fullPath: '/best-strikers'
      preLoaderRoute: typeof BestStrikersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-players': {
      id: '/best-players'
      path: '/best-players'
      fullPath: '/best-players'
      preLoaderRoute: typeof BestPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tournaments': {
      id: '/_authenticated/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof AuthenticatedTournamentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rankings': {
      id: '/_authenticated/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AuthenticatedRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-stats': {
      id: '/_authenticated/my-stats'
      path: '/my-stats'
      fullPath: '/my-stats'
      preLoaderRoute: typeof AuthenticatedMyStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches': {
      id: '/_authenticated/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/join-team': {
      id: '/_authenticated/join-team'
      path: '/join-team'
      fullPath: '/join-team'
      preLoaderRoute: typeof AuthenticatedJoinTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tournaments/': {
      id: '/_authenticated/tournaments/'
      path: '/'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof AuthenticatedTournamentsIndexRouteImport
      parentRoute: typeof AuthenticatedTournamentsRoute
    }
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthenticatedTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedTeamsRoute
    }
    '/_authenticated/matches/': {
      id: '/_authenticated/matches/'
      path: '/'
      fullPath: '/matches/'
      preLoaderRoute: typeof AuthenticatedMatchesIndexRouteImport
      parentRoute: typeof AuthenticatedMatchesRoute
    }
    '/_authenticated/tournaments/new': {
      id: '/_authenticated/tournaments/new'
      path: '/new'
      fullPath: '/tournaments/new'
      preLoaderRoute: typeof AuthenticatedTournamentsNewRouteImport
      parentRoute: typeof AuthenticatedTournamentsRoute
    }
    '/_authenticated/tournaments/$tournamentId': {
      id: '/_authenticated/tournaments/$tournamentId'
      path: '/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof AuthenticatedTournamentsTournamentIdRouteImport
      parentRoute: typeof AuthenticatedTournamentsRoute
    }
    '/_authenticated/teams/new': {
      id: '/_authenticated/teams/new'
      path: '/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof AuthenticatedTeamsNewRouteImport
      parentRoute: typeof AuthenticatedTeamsRoute
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedTeamsRoute
    }
    '/_authenticated/matches/new': {
      id: '/_authenticated/matches/new'
      path: '/new'
      fullPath: '/matches/new'
      preLoaderRoute: typeof AuthenticatedMatchesNewRouteImport
      parentRoute: typeof AuthenticatedMatchesRoute
    }
    '/_authenticated/teams/$teamId/matches': {
      id: '/_authenticated/teams/$teamId/matches'
      path: '/matches'
      fullPath: '/teams/$teamId/matches'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdMatchesRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRoute
    }
    '/_authenticated/matches/$matchId/squad': {
      id: '/_authenticated/matches/$matchId/squad'
      path: '/$matchId/squad'
      fullPath: '/matches/$matchId/squad'
      preLoaderRoute: typeof AuthenticatedMatchesMatchIdSquadRouteImport
      parentRoute: typeof AuthenticatedMatchesRoute
    }
    '/_authenticated/matches/$matchId/score': {
      id: '/_authenticated/matches/$matchId/score'
      path: '/$matchId/score'
      fullPath: '/matches/$matchId/score'
      preLoaderRoute: typeof AuthenticatedMatchesMatchIdScoreRouteImport
      parentRoute: typeof AuthenticatedMatchesRoute
    }
  }
}

interface AuthenticatedMatchesRouteChildren {
  AuthenticatedMatchesNewRoute: typeof AuthenticatedMatchesNewRoute
  AuthenticatedMatchesIndexRoute: typeof AuthenticatedMatchesIndexRoute
  AuthenticatedMatchesMatchIdScoreRoute: typeof AuthenticatedMatchesMatchIdScoreRoute
  AuthenticatedMatchesMatchIdSquadRoute: typeof AuthenticatedMatchesMatchIdSquadRoute
}

const AuthenticatedMatchesRouteChildren: AuthenticatedMatchesRouteChildren = {
  AuthenticatedMatchesNewRoute: AuthenticatedMatchesNewRoute,
  AuthenticatedMatchesIndexRoute: AuthenticatedMatchesIndexRoute,
  AuthenticatedMatchesMatchIdScoreRoute: AuthenticatedMatchesMatchIdScoreRoute,
  AuthenticatedMatchesMatchIdSquadRoute: AuthenticatedMatchesMatchIdSquadRoute,
}

const AuthenticatedMatchesRouteWithChildren =
  AuthenticatedMatchesRoute._addFileChildren(AuthenticatedMatchesRouteChildren)

interface AuthenticatedTeamsTeamIdRouteChildren {
  AuthenticatedTeamsTeamIdMatchesRoute: typeof AuthenticatedTeamsTeamIdMatchesRoute
}

const AuthenticatedTeamsTeamIdRouteChildren: AuthenticatedTeamsTeamIdRouteChildren =
  {
    AuthenticatedTeamsTeamIdMatchesRoute: AuthenticatedTeamsTeamIdMatchesRoute,
  }

const AuthenticatedTeamsTeamIdRouteWithChildren =
  AuthenticatedTeamsTeamIdRoute._addFileChildren(
    AuthenticatedTeamsTeamIdRouteChildren,
  )

interface AuthenticatedTeamsRouteChildren {
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRouteWithChildren
  AuthenticatedTeamsNewRoute: typeof AuthenticatedTeamsNewRoute
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute
}

const AuthenticatedTeamsRouteChildren: AuthenticatedTeamsRouteChildren = {
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRouteWithChildren,
  AuthenticatedTeamsNewRoute: AuthenticatedTeamsNewRoute,
  AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
}

const AuthenticatedTeamsRouteWithChildren =
  AuthenticatedTeamsRoute._addFileChildren(AuthenticatedTeamsRouteChildren)

interface AuthenticatedTournamentsRouteChildren {
  AuthenticatedTournamentsTournamentIdRoute: typeof AuthenticatedTournamentsTournamentIdRoute
  AuthenticatedTournamentsNewRoute: typeof AuthenticatedTournamentsNewRoute
  AuthenticatedTournamentsIndexRoute: typeof AuthenticatedTournamentsIndexRoute
}

const AuthenticatedTournamentsRouteChildren: AuthenticatedTournamentsRouteChildren =
  {
    AuthenticatedTournamentsTournamentIdRoute:
      AuthenticatedTournamentsTournamentIdRoute,
    AuthenticatedTournamentsNewRoute: AuthenticatedTournamentsNewRoute,
    AuthenticatedTournamentsIndexRoute: AuthenticatedTournamentsIndexRoute,
  }

const AuthenticatedTournamentsRouteWithChildren =
  AuthenticatedTournamentsRoute._addFileChildren(
    AuthenticatedTournamentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedJoinTeamRoute: typeof AuthenticatedJoinTeamRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMatchesRoute: typeof AuthenticatedMatchesRouteWithChildren
  AuthenticatedMyStatsRoute: typeof AuthenticatedMyStatsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRankingsRoute: typeof AuthenticatedRankingsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRouteWithChildren
  AuthenticatedTournamentsRoute: typeof AuthenticatedTournamentsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedJoinTeamRoute: AuthenticatedJoinTeamRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMatchesRoute: AuthenticatedMatchesRouteWithChildren,
  AuthenticatedMyStatsRoute: AuthenticatedMyStatsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRankingsRoute: AuthenticatedRankingsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRouteWithChildren,
  AuthenticatedTournamentsRoute: AuthenticatedTournamentsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BestPlayersRoute: BestPlayersRoute,
  BestStrikersRoute: BestStrikersRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogSlugRoute: BlogSlugRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
